[package]
name = "zhdanov_wire_world"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git" }
anyhow = { version = "1.0" }
indexmap = { version = "1.9.3" }