[package]
name = "zhdanov_website_terminal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"

[dependencies.zhdanov_website_core]
path = "../core"
